# Staging overlay
# Chapter 3: "It Works on My Machine"

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - configmap.yaml
  - secrets.yaml

replicas:
  - name: notification-service
    count: 2

images:
  - name: techflow/notification-service
    newTag: v1.2.0

commonLabels:
  environment: staging
